name: Deploy Firebase Functions & Hosting

on:
  push:
    branches: [main] # or 'master', depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > "${HOME}/firebase-key.json"

      - name: Firebase Login
        run: firebase auth:login:ci --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        run: |
          cd functions
          npm install
          cd ..
          firebase functions:secrets:set TWITCH_CLIENT_ID --project your-project-id <<< "${TWITCH_CLIENT_ID}"
          firebase functions:secrets:set TWITCH_CLIENT_SECRET --project your-project-id <<< "${TWITCH_CLIENT_SECRET}"
          firebase deploy --only functions,hosting --project your-project-id
